export class CreatePremiereDto {
    masterId: string;
    childMasterId: string;
    primary_contactname:string ;
    primary_useremail: string;
    stageStatus: number;
    primary_mobilenumber:string ;
    primary_position: string;
    reportingManagerEmail: string;
    leadname: string;
    leadEmail: string;
    leadmobilenumber: string;
    businessname:string;
  businessownername:string;
  how_to_pronounce_names:string;
  opening_time:string;
  time_zone:string;
  streetaddress1:string;
  streetaddress2: string;
  city1: string;
  state1: string;
  pincode1:string;
  websitelink:string ;
  links_for_scheduling:string;
  cost_of_consultation:string;
  schedule_existing_clients:string;
  attempt_to_transfer:string;
  number_of_transfer:string;
  time_of_transfer:string;
  who_should_transfer:string;
  services_available:string;
  if_outsideservices_offered:string;
  brief_business_summary:string;
  Employee_list:string;
  patients_find_office:string;
  seek_integrate_CRM:string;
  Additional_notes:string;
  subject:string;
  pdf:string;
  formtype:string;
}
