export class CreatePpcRankroverDto {
    biling_email:string;
   software:string;
   oms_manager_name:string;
   masterId:string; 
  childMasterId:string; 
  primary_contactname:string; 
  primary_useremail:string; 
  stageStatus:number; 
  primary_mobilenumber:string; 
  primary_position:string; 
  reportingManagerEmail:string; 
  leadname:string; 
  leadEmail:string; 
  leadmobilenumber:string; 
  businessname:string; 
  streetaddress1:string;
  streetaddress2:string;
  city1:string; 
  state1:string; 
  pincode1:string; 
  websitelink:string;
  domain:string;
  googleaccount:string; 
  uploadimage:string; 
  pdf:string;
  streetaddress_location_1: string;
  streetaddress_location_2: string;
  streetaddress_location_3: string;
  streetaddress1_location_1: string;
  streetaddress1_location_2: string;
  streetaddress1_location_3: string;
  City_location_1: string;
  City_location_2: string;
  City_location_3: string;
  State_location_1: string;
  State_location_2: string;
  State_location_3: string;
  Zip_location_1: string;
  Zip_location_2: string;
  Zip_location_3: string;
  number_location_1: string;
  number_location_2: string;
  number_location_3: string;
  subject:string;
  formtype:string;
}
